# Site settings
title:       一点修为
email:       
author:      HughCraft
description: "A Bit Craft"
baseurl:     ""
url:         "http://ABitCraft.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Build settings
markdown:     kramdown
kramdown:
  input:  GFM
  enable_coderay: true
  syntax_highlighter: coderay
permalink:     /:title
paginate:     6
sass:
  compressed: true
gems:
  - jekyll-sitemap
  - jekyll-paginate
